title: TramFishers
author: Fraser Smith
subtitle: Words and Images and Stuff

url: "https://www.tramfishers.com"
baseurl: ""

imagebase: "https://raw.githubusercontent.com/FrasSmith/wallpapers/master/images/"

# profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

remote_theme: carlosperate/jekyll-theme-rtd

footer_text: Fraser Smith, TramFishers, :year.

permalink: /:year/:month/:day/:title

excerpt_separator: <!--more-->

sass:
    style: compressed
    sass_dir: css

plugins:
  - jekyll-feed
  - jekyll-seo-tag
