title: TramFishers
author: Fraser Smith
subtitle: Words and Images and Stuff

url: ""
baseurl: ""

# profile-picture: assets/profile.jpg
# favicon_location: assets/favicon.ico

permalink: /:year/:month/:day/:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
