title: TramFishers
author: Fraser Smith
subtitle: Words and Images and Stuff

url: "https://www.tramfishers.com"
baseurl: ""

# imagebase: "https://raw.githubusercontent.com/FrasSmith/wallpapers/master/images/"

# profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

footer_text: Copyright 2020, Fraser Smith, TramFishers.

permalink: /:year/:month/:day/:title

excerpt_separator: <!--more-->

sass:
    style: compressed
    sass_dir: css

plugins:
  - jekyll-feed
  - jekyll-seo-tag

navbar:
 - name: "About"
   link: "about"
 - name: "Tags"
   link: "tags"
 - name: "Feed"
   link: "feed"
#  - name: "Wallpapers"
#   link: "wallpapers"

